### ISSUE TITLE
The server and commandline version predictions are not same

### ISSUE THREAD

**Issue by Rohit-Satyam** [raghavagps/transfacpred#2]
Hi @raghavagps @sumeetpatiyal 

While going through the previous analysis that I did using your web server (because I was unable to run transfacpred locally but now I can run it locally) I realized that the predictions and scores are different.

For example for protein PF3D7_0322200.1 I see that your webserver says that it a TF based on Hybrid model: 

![Screenshot from 2024-04-16 14-11-49](https://github.com/raghavagps/transfacpred/assets/55479480/f9f90f10-3976-484a-bef0-5d743b716f91)

While your command line results say it is not.

![Screenshot from 2024-04-16 14-12-35](https://github.com/raghavagps/transfacpred/assets/55479480/83e1638a-6764-4412-83d3-334a01517a6f)

Blastp score appears to not agree for some reason (I am using version `blastp: 2.15.0+` ) which is the latest version. Can you please address the discrepancy!!

Besides, can you say something about the probability threshold for the hybrid model like what is more stringent and less stringent because I have been using default -0.38 ?

**Comment by Rohit-Satyam** [comment]
@raghavagps @sumeetpatiyal I was wondering if you had time to check the query I raised!!

**Comment by sumeetpatiyal** [comment]
Dear Rohit,

Thank you raising this issue. You are right that the issue is due to the discrepancies in the version of the blastp.The version used in the web server is blastp:2.2.29+. 
The default value that we have used in the method which is -0.38, is the one which resulted in the balanced sensitivity and specificity. In simpler words, at the threshold of -0.38, the model was able to predict the higher percentage of positive and negative samples correctly. This threshold is adjustable as per the user desires.

Thank You
Sumeet Patiyal

**Comment by Rohit-Satyam** [comment]
@sumeetpatiyal @raghavagps 

I think the latest BLAST executable available at [bioconda](https://anaconda.org/bioconda/blast) is `blastp: 2.15.0+`. Was there a specific reason to use this release? While going through the release log [here](https://www.ncbi.nlm.nih.gov/books/NBK131777/) I realised that the Blastp your server is using is quite old release (`2014-10-08` release which is 17 release behind). I hope you will agree on this when I say using a decade old blast+ utility will make people roll their eyes and will also generate inconsistent and spurious results.
